/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shenby.swig;

public class LandFace {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LandFace(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LandFace obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(LandFace obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LandXmlJNI.delete_LandFace(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LandFace() {
    this(LandXmlJNI.new_LandFace(), true);
  }

  public void setX1(double value) {
    LandXmlJNI.LandFace_x1_set(swigCPtr, this, value);
  }

  public double getX1() {
    return LandXmlJNI.LandFace_x1_get(swigCPtr, this);
  }

  public void setY1(double value) {
    LandXmlJNI.LandFace_y1_set(swigCPtr, this, value);
  }

  public double getY1() {
    return LandXmlJNI.LandFace_y1_get(swigCPtr, this);
  }

  public void setZ1(double value) {
    LandXmlJNI.LandFace_z1_set(swigCPtr, this, value);
  }

  public double getZ1() {
    return LandXmlJNI.LandFace_z1_get(swigCPtr, this);
  }

  public void setX2(double value) {
    LandXmlJNI.LandFace_x2_set(swigCPtr, this, value);
  }

  public double getX2() {
    return LandXmlJNI.LandFace_x2_get(swigCPtr, this);
  }

  public void setY2(double value) {
    LandXmlJNI.LandFace_y2_set(swigCPtr, this, value);
  }

  public double getY2() {
    return LandXmlJNI.LandFace_y2_get(swigCPtr, this);
  }

  public void setZ2(double value) {
    LandXmlJNI.LandFace_z2_set(swigCPtr, this, value);
  }

  public double getZ2() {
    return LandXmlJNI.LandFace_z2_get(swigCPtr, this);
  }

  public void setX3(double value) {
    LandXmlJNI.LandFace_x3_set(swigCPtr, this, value);
  }

  public double getX3() {
    return LandXmlJNI.LandFace_x3_get(swigCPtr, this);
  }

  public void setY3(double value) {
    LandXmlJNI.LandFace_y3_set(swigCPtr, this, value);
  }

  public double getY3() {
    return LandXmlJNI.LandFace_y3_get(swigCPtr, this);
  }

  public void setZ3(double value) {
    LandXmlJNI.LandFace_z3_set(swigCPtr, this, value);
  }

  public double getZ3() {
    return LandXmlJNI.LandFace_z3_get(swigCPtr, this);
  }

}
