/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shenby.swig;

public class LandXmlReadProgressListener {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LandXmlReadProgressListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LandXmlReadProgressListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(LandXmlReadProgressListener obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LandXmlJNI.delete_LandXmlReadProgressListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    LandXmlJNI.LandXmlReadProgressListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    LandXmlJNI.LandXmlReadProgressListener_change_ownership(this, swigCPtr, true);
  }

  public LandXmlReadProgressListener() {
    this(LandXmlJNI.new_LandXmlReadProgressListener(), true);
    LandXmlJNI.LandXmlReadProgressListener_director_connect(this, swigCPtr, true, true);
  }

  public void onReadStart() {
    if (getClass() == LandXmlReadProgressListener.class) LandXmlJNI.LandXmlReadProgressListener_onReadStart(swigCPtr, this); else LandXmlJNI.LandXmlReadProgressListener_onReadStartSwigExplicitLandXmlReadProgressListener(swigCPtr, this);
  }

  public void onReadProgress(int progress) {
    if (getClass() == LandXmlReadProgressListener.class) LandXmlJNI.LandXmlReadProgressListener_onReadProgress(swigCPtr, this, progress); else LandXmlJNI.LandXmlReadProgressListener_onReadProgressSwigExplicitLandXmlReadProgressListener(swigCPtr, this, progress);
  }

  public void onReadFinish() {
    if (getClass() == LandXmlReadProgressListener.class) LandXmlJNI.LandXmlReadProgressListener_onReadFinish(swigCPtr, this); else LandXmlJNI.LandXmlReadProgressListener_onReadFinishSwigExplicitLandXmlReadProgressListener(swigCPtr, this);
  }

}
