/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shenby.swig;

public class LandXmlJNI {
  public final static native long new_LandFace();
  public final static native void delete_LandFace(long jarg1);
  public final static native void LandFace_x1_set(long jarg1, LandFace jarg1_, double jarg2);
  public final static native double LandFace_x1_get(long jarg1, LandFace jarg1_);
  public final static native void LandFace_y1_set(long jarg1, LandFace jarg1_, double jarg2);
  public final static native double LandFace_y1_get(long jarg1, LandFace jarg1_);
  public final static native void LandFace_z1_set(long jarg1, LandFace jarg1_, double jarg2);
  public final static native double LandFace_z1_get(long jarg1, LandFace jarg1_);
  public final static native void LandFace_x2_set(long jarg1, LandFace jarg1_, double jarg2);
  public final static native double LandFace_x2_get(long jarg1, LandFace jarg1_);
  public final static native void LandFace_y2_set(long jarg1, LandFace jarg1_, double jarg2);
  public final static native double LandFace_y2_get(long jarg1, LandFace jarg1_);
  public final static native void LandFace_z2_set(long jarg1, LandFace jarg1_, double jarg2);
  public final static native double LandFace_z2_get(long jarg1, LandFace jarg1_);
  public final static native void LandFace_x3_set(long jarg1, LandFace jarg1_, double jarg2);
  public final static native double LandFace_x3_get(long jarg1, LandFace jarg1_);
  public final static native void LandFace_y3_set(long jarg1, LandFace jarg1_, double jarg2);
  public final static native double LandFace_y3_get(long jarg1, LandFace jarg1_);
  public final static native void LandFace_z3_set(long jarg1, LandFace jarg1_, double jarg2);
  public final static native double LandFace_z3_get(long jarg1, LandFace jarg1_);
  public final static native long new_LandXmlReader();
  public final static native void delete_LandXmlReader(long jarg1);
  public final static native void LandXmlReader_setLandXml(long jarg1, LandXmlReader jarg1_, String jarg2);
  public final static native boolean LandXmlReader_readData(long jarg1, LandXmlReader jarg1_);
  public final static native int LandXmlReader_getCount(long jarg1, LandXmlReader jarg1_);
  public final static native long LandXmlReader_loadLandFace(long jarg1, LandXmlReader jarg1_, int jarg2);
  public final static native void LandXmlReader_close(long jarg1, LandXmlReader jarg1_);
}
