/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shenby.swig;

public class NCoordinate {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NCoordinate(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NCoordinate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(NCoordinate obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LandXmlJNI.delete_NCoordinate(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(int value) {
    LandXmlJNI.NCoordinate_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return LandXmlJNI.NCoordinate_id_get(swigCPtr, this);
  }

  public void setX(double value) {
    LandXmlJNI.NCoordinate_x_set(swigCPtr, this, value);
  }

  public double getX() {
    return LandXmlJNI.NCoordinate_x_get(swigCPtr, this);
  }

  public void setY(double value) {
    LandXmlJNI.NCoordinate_y_set(swigCPtr, this, value);
  }

  public double getY() {
    return LandXmlJNI.NCoordinate_y_get(swigCPtr, this);
  }

  public void setZ(double value) {
    LandXmlJNI.NCoordinate_z_set(swigCPtr, this, value);
  }

  public double getZ() {
    return LandXmlJNI.NCoordinate_z_get(swigCPtr, this);
  }

  public NCoordinate() {
    this(LandXmlJNI.new_NCoordinate__SWIG_0(), true);
  }

  public NCoordinate(int id, double x, double y, double z) {
    this(LandXmlJNI.new_NCoordinate__SWIG_1(id, x, y, z), true);
  }

}
