/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shenby_pacwth_echo_EchoServerActivity */

#ifndef _Included_com_shenby_pacwth_echo_EchoServerActivity
#define _Included_com_shenby_pacwth_echo_EchoServerActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shenby_pacwth_echo_EchoServerActivity
 * Method:    nativeStartTcpServer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_shenby_pacwth_echo_EchoServerActivity_nativeStartTcpServer
        (JNIEnv *, jobject, jint);

/*
 * Class:     com_shenby_pacwth_echo_EchoServerActivity
 * Method:    nativeStartUdpServer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_shenby_pacwth_echo_EchoServerActivity_nativeStartUdpServer
        (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
