/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_AsyncProvider_WRAP_H_
#define SWIG_AsyncProvider_WRAP_H_

class SwigDirector_AsyncUidProvider : public AsyncUidProvider, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_AsyncUidProvider(JNIEnv *jenv);
    virtual ~SwigDirector_AsyncUidProvider();
    virtual void onUid(uid_t uid);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};


#endif
