/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_LandXml_WRAP_H_
#define SWIG_LandXml_WRAP_H_

class SwigDirector_LandXmlReadProgressListener : public LandXmlReadProgressListener, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_LandXmlReadProgressListener(JNIEnv *jenv);
    virtual ~SwigDirector_LandXmlReadProgressListener();
    virtual void onReadStart();
    virtual void onReadProgress(int progress);
    virtual void onReadFinish();
public:
    bool swig_overrides(int n) {
      return (n < 3 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<3> swig_override;
};


#endif
