/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shenby_pacwth_chap07_threads_MainActivity */

#ifndef _Included_com_shenby_pacwth_chap07_threads_MainActivity
#define _Included_com_shenby_pacwth_chap07_threads_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shenby_pacwth_chap07_threads_MainActivity
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_shenby_pacwth_chap07_threads_MainActivity_nativeInit
        (JNIEnv *, jobject);

/*
 * Class:     com_shenby_pacwth_chap07_threads_MainActivity
 * Method:    nativeFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_shenby_pacwth_chap07_threads_MainActivity_nativeFree
        (JNIEnv *, jobject);

/*
 * Class:     com_shenby_pacwth_chap07_threads_MainActivity
 * Method:    nativeWorker
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_shenby_pacwth_chap07_threads_MainActivity_nativeWorker
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_shenby_pacwth_chap07_threads_MainActivity
 * Method:    posixThreads
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_shenby_pacwth_chap07_threads_MainActivity_posixThreads
        (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
