/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shenby.swig;

public class CppClassJNI {
  public final static native long new_Student__SWIG_0();
  public final static native long new_Student__SWIG_1(int jarg1);
  public final static native long new_Student__SWIG_2(int jarg1, double jarg2);
  public final static native void delete_Student(long jarg1);
  public final static native void Student_show(long jarg1, Student jarg1_);
  public final static native void Student_id_set(long jarg1, Student jarg1_, int jarg2);
  public final static native int Student_id_get(long jarg1, Student jarg1_);
}
