/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shenby.swig;

public class CppStruct {
  public static void drawByPointer(PointCpp p) {
    CppStructJNI.drawByPointer(PointCpp.getCPtr(p), p);
  }

  public static void drawByReference(PointCpp p) {
    CppStructJNI.drawByReference(PointCpp.getCPtr(p), p);
  }

  public static void drawByValue(PointCpp pointCpp) {
    CppStructJNI.drawByValue(PointCpp.getCPtr(pointCpp), pointCpp);
  }

  public static void func(int a, int b, int c) {
    CppStructJNI.func__SWIG_0(a, b, c);
  }

  public static void func(int a, int b) {
    CppStructJNI.func__SWIG_1(a, b);
  }

  public static void func(int a) {
    CppStructJNI.func__SWIG_2(a);
  }

  public static void func() {
    CppStructJNI.func__SWIG_3();
  }

}
