/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shenby.swig;

public class CppStructJNI {
  public final static native void PointCpp_x_set(long jarg1, PointCpp jarg1_, int jarg2);
  public final static native int PointCpp_x_get(long jarg1, PointCpp jarg1_);
  public final static native void PointCpp_y_set(long jarg1, PointCpp jarg1_, int jarg2);
  public final static native int PointCpp_y_get(long jarg1, PointCpp jarg1_);
  public final static native long new_PointCpp();
  public final static native void delete_PointCpp(long jarg1);
  public final static native void drawByPointer(long jarg1, PointCpp jarg1_);
  public final static native void drawByReference(long jarg1, PointCpp jarg1_);
  public final static native void drawByValue(long jarg1, PointCpp jarg1_);
}
