/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shenby.swig;

public class MyEnumJNI {
  public final static native int ONE_get();
  public final static native int TWO_get();
  public final static native int THREE_get();
  public final static native int FOUR_get();
  public final static native int A_get();
  public final static native int B_get();
  public final static native int U1_get();
  public final static native int U2_get();
  public final static native int U3_get();
  public final static native int U4_get();
  public final static native int SUNDAY_get();
  public final static native int MONDAY_get();
  public final static native int TUESDAY_get();
  public final static native int WEDNESDAY_get();
  public final static native int THURSDAY_get();
  public final static native int FRIDAY_get();
  public final static native int SATURDAY_get();
}
