/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shenby.swig;

public class UnixJNI {
  public final static native long getuid() throws java.lang.IllegalAccessException;
  public final static native void counter_set(int jarg1);
  public final static native int counter_get();
  public final static native int MAX_WIDTH_get();
  public final static native int MAX_HEIGHT_get();
  public final static native int MIN_HEIGHT_get();
  public final static native int readOnly_get();
  public final static native void readWrite_set(int jarg1);
  public final static native int readWrite_get();
}
