/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shenby.swig;

public final class Week {
  public final static int SUNDAY = MyEnumJNI.SUNDAY_get();
  public final static int MONDAY = MyEnumJNI.MONDAY_get();
  public final static int TUESDAY = MyEnumJNI.TUESDAY_get();
  public final static int WEDNESDAY = MyEnumJNI.WEDNESDAY_get();
  public final static int THURSDAY = MyEnumJNI.THURSDAY_get();
  public final static int FRIDAY = MyEnumJNI.FRIDAY_get();
  public final static int SATURDAY = MyEnumJNI.SATURDAY_get();
}

