/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shenby.swig;

public class LandXmlReader {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LandXmlReader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LandXmlReader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(LandXmlReader obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LandXmlJNI.delete_LandXmlReader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LandXmlReader() {
    this(LandXmlJNI.new_LandXmlReader(), true);
  }

  public void setLandXml(String path) {
    LandXmlJNI.LandXmlReader_setLandXml(swigCPtr, this, path);
  }

  public boolean readData() {
    return LandXmlJNI.LandXmlReader_readData(swigCPtr, this);
  }

  public int getCount() {
    return LandXmlJNI.LandXmlReader_getCount(swigCPtr, this);
  }

  public double[] getSjwData(int index) {
return LandXmlJNI.LandXmlReader_getSjwData(swigCPtr, this, index);
}

  public void close() {
    LandXmlJNI.LandXmlReader_close(swigCPtr, this);
  }

}
