/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shenby.swig;

public class LandXmlJNI {
  public final static native long new_LandXmlReader();
  public final static native void delete_LandXmlReader(long jarg1);
  public final static native void LandXmlReader_setLandXml(long jarg1, LandXmlReader jarg1_, String jarg2);
  public final static native boolean LandXmlReader_readData(long jarg1, LandXmlReader jarg1_);
  public final static native int LandXmlReader_getCount(long jarg1, LandXmlReader jarg1_);
  public final static native double[] LandXmlReader_getSjwData(long jarg1, LandXmlReader jarg1_, int jarg2);
  public final static native void LandXmlReader_close(long jarg1, LandXmlReader jarg1_);
}
