/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shenby.swig;

public interface MyEnumConstants {
  public final static int ONE = MyEnumJNI.ONE_get();
  public final static int TWO = MyEnumJNI.TWO_get();
  public final static int THREE = MyEnumJNI.THREE_get();
  public final static int FOUR = MyEnumJNI.FOUR_get();

}
