/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shenby.swig;

public final class Numbers {
  public final static Numbers A = new Numbers("A", MyEnumJNI.A_get());
  public final static Numbers B = new Numbers("B", MyEnumJNI.B_get());
  public final static Numbers C = new Numbers("C");
  public final static Numbers D = new Numbers("D");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Numbers swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Numbers.class + " with value " + swigValue);
  }

  private Numbers(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Numbers(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Numbers(String swigName, Numbers swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Numbers[] swigValues = { A, B, C, D };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

