/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shenby.swig;

public class Student {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Student(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Student obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CppClassJNI.delete_Student(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Student() {
    this(CppClassJNI.new_Student__SWIG_0(), true);
  }

  public Student(int id) {
    this(CppClassJNI.new_Student__SWIG_1(id), true);
  }

  public Student(int id, double weight) {
    this(CppClassJNI.new_Student__SWIG_2(id, weight), true);
  }

  public void show() {
    CppClassJNI.Student_show(swigCPtr, this);
  }

  public void setId(int value) {
    CppClassJNI.Student_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return CppClassJNI.Student_id_get(swigCPtr, this);
  }

}
