/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shenby.swig;

public interface UnixConstants {
  public final static int MAX_WIDTH = UnixJNI.MAX_WIDTH_get();
  public final static int MAX_HEIGHT = UnixJNI.MAX_HEIGHT_get();
  public final static int MIN_WIDTH = 320;
  public final static int MIN_HEIGHT = UnixJNI.MIN_HEIGHT_get();
}
