/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shenby.swig;

public final class UnsafeNumbers {
  public final static int U1 = MyEnumJNI.U1_get();
  public final static int U2 = MyEnumJNI.U2_get();
  public final static int U3 = MyEnumJNI.U3_get();
  public final static int U4 = MyEnumJNI.U4_get();
}

